manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: chatblanc77
      url-base: https://github.com/chatblanc77
  projects:
    - name: zmk-config
      remote: chatblanc77
      revision: sofle-v2
      import: app/west.yml
  self:
    path: config
